version: '3.9'

services:
  app:
    container_name: "app"
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgresql+asyncpg://postgres:postgres@db:5432/postgres
      MINIO_ACCESS_KEY: minio-user
      MINIO_SECRET_KEY: minio-password
      MINIO_BUCKET: main-bucket
    depends_on:
      - db
      - storage
    networks:
      - custom

  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - custom

  test-db:
    container_name: "test-db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: test-postgres
      POSTGRES_PASSWORD: test-postgres
      POSTGRES_DB: test-postgres
    ports:
      - "5434:5432"
    networks:
      - custom

  storage:
    container_name: "storage"
    image: minio/minio
    command: ["server", "/data"]
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio-user
      MINIO_ROOT_PASSWORD: minio-password
      MINIO_ADDRESS: :9000
      MINIO_CONSOLE_ADDRESS: :9001
    volumes:
      - minio-data:/data
    networks:
      - custom

volumes:
  minio-data:

networks:
  custom:
    driver: bridge