services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - custom

  minio:
    container_name: "storage"
    image: minio/minio
    command: ["server", "/data"]
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio-user
      MINIO_ROOT_PASSWORD: minio-password
      MINIO_ADDRESS: :9000
      MINIO_CONSOLE_ADDRESS: :9001
    volumes:
      - minio-data:/data
    networks:
      - custom

volumes:
  minio-data:

networks:
  custom:
    driver: bridge