"""empty message

Revision ID: 481eb39b55ca
Revises: bf044ad13900
Create Date: 2025-01-29 19:25:09.999835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481eb39b55ca'
down_revision = 'bf044ad13900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_storages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_fk', sa.UUID(), nullable=False),
    sa.Column('bucket_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('files', sa.Column('storage_id', sa.UUID(), nullable=False))
    op.add_column('files', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('files', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'files', 'user_storages', ['storage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'updated_at')
    op.drop_column('files', 'created_at')
    op.drop_column('files', 'storage_id')
    op.drop_table('user_storages')
    op.drop_table('users')
    # ### end Alembic commands ###
