"""Initial migration

<<<<<<<< HEAD:src/alembic/versions/89fb153e9a9e_initial_migration.py
Revision ID: 89fb153e9a9e
Revises: 
Create Date: 2024-12-21 17:23:46.182208
========
Revision ID: 51313684e8fd
Revises: 
Create Date: 2024-12-23 15:40:01.629093
>>>>>>>> project-refactoring:src/alembic/versions/51313684e8fd_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:src/alembic/versions/89fb153e9a9e_initial_migration.py
revision = '89fb153e9a9e'
========
revision = '51313684e8fd'
>>>>>>>> project-refactoring:src/alembic/versions/51313684e8fd_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('filesize', sa.Integer(), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('etag', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
