"""empty message

Revision ID: 51425681a1de
Revises: 65d33586aed4
Create Date: 2025-02-05 23:33:22.050357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51425681a1de'
down_revision = '65d33586aed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
