"""empty message

Revision ID: 65d33586aed4
Revises: b6dce447126d
Create Date: 2025-02-05 23:13:21.777406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d33586aed4'
down_revision = 'b6dce447126d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
