"""empty message

Revision ID: 72250e325841
Revises: e434194b68bf
Create Date: 2025-02-07 22:57:42.518383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72250e325841'
down_revision = 'e434194b68bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
