"""empty message

Revision ID: 993e6195f17b
Revises: 
Create Date: 2024-09-06 19:16:01.702531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993e6195f17b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_models',
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_models_filename'), 'file_models', ['filename'], unique=False)
    op.create_index(op.f('ix_file_models_path'), 'file_models', ['path'], unique=False)
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.drop_index(op.f('ix_file_models_path'), table_name='file_models')
    op.drop_index(op.f('ix_file_models_filename'), table_name='file_models')
    op.drop_table('file_models')
    # ### end Alembic commands ###
