"""empty message

Revision ID: b5f05328256b
Revises: 1ad7554ebfee
Create Date: 2024-08-29 21:07:51.390662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f05328256b'
down_revision = '1ad7554ebfee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_models',
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_models_filename'), 'file_models', ['filename'], unique=False)
    op.create_index(op.f('ix_file_models_path'), 'file_models', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_models_path'), table_name='file_models')
    op.drop_index(op.f('ix_file_models_filename'), table_name='file_models')
    op.drop_table('file_models')
    # ### end Alembic commands ###
