"""empty message

Revision ID: bf044ad13900
Revises: 4218a7673a65
Create Date: 2025-01-22 14:03:58.690458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf044ad13900'
down_revision = '4218a7673a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_url', sa.String(), nullable=False))
    op.drop_column('files', 'last_modified')
    op.drop_column('files', 'filesize')
    op.drop_column('files', 'content_type')
    op.drop_column('files', 'etag')
    op.drop_column('files', 'filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('files', sa.Column('etag', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('files', sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('files', sa.Column('filesize', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('files', sa.Column('last_modified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('files', 'file_url')
    # ### end Alembic commands ###
