"""empty message

Revision ID: d4de04d2b759
Revises: eef28d9de6d8
Create Date: 2024-09-08 23:22:24.429710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4de04d2b759'
down_revision = 'eef28d9de6d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('filesize', sa.Integer(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('etag', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('file_models')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_models',
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filesize', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('etag', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='file_models_pkey')
    )
    op.drop_table('files')
    # ### end Alembic commands ###
