"""empty message

Revision ID: d98eded5570e
Revises: 481eb39b55ca
Create Date: 2025-02-01 14:02:25.422225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98eded5570e'
down_revision = '481eb39b55ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_fk', sa.UUID(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('files', 'storage_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'storage_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('sessions')
    # ### end Alembic commands ###
